site_name: My Docs
theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'pink'
    background: 'white'
    surface: 'grey'
    error: 'red'

extra_css:
  - 'overrides/extra.css'
custom_dir: 'overrides'